### ISSUE TITLE
table_formatter - allow for null entries in rows/columns

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/gen_dw_format#30]
Allow the user to format only rows or only columns.
Right now, the user cannot format solely rows without having to format columns as well.

**Possible solution:**
Add a "No rows/columns"/"None of the rows/columns" dropdown entry in the "Rows/Columns to perform actions on" dropdown.

If this functionality already exists, make it more explicit for a better user experience.

**Comment by hughdingb58** [comment]
Implemented - this would be done by selecting "all rows/columns" for the dimension that doesn't matter. If you only need to specify rows for example, then "all columns" would go through every value in the rows to edit. I clarified this in the html page/readme.
