### ISSUE TITLE
footnote_formatter - Clarification suggestions

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/gen_dw_format#48]
**Code:**
- Add 1 to the index (since VS Code and Dreamweaver's line numbering starts at 1)

**HTML Page:**
- Clarify which HTML document to upload (is this after the initial Dreamweaver paste? If so, would the user change the "Top footnote formatting" and "Bottom footnote formatting" to "Dreamweaver-generated footnotes? This is a bit unclear)
- If the user leaves the indexing blank (start to finish line numbers), does this mean they are formatter all the footnotes in the file? If so, could probably specify this.
- Provide information on what this tool does at the top of the page as opposed to the bottom
- Clarify what "Group containing content" means (this is explained in the readme but it's still relatively unclear. Give an example of this somewhere between the HTML page and the readme, and provide a brief explanation in the HTML page)

**readme:**
- "When formatting footnotes for a Dreamweaver paste, I recommend formatting inner footnote subsections first" --> would the second run through of this tool affect the inner footnote subsections? If so, what would the user input for line numbers such that the inner footnote subsections aren't affected?
- "If you do change the footnote IDs, I recommend constructing footnote ids out of numbers, letters, and regular dashes “-“, e.g. “fnb-tbl1” for footnotes in table 1, as this is what is assumed by the tool’s default regex statements." --> maybe briefly specify this in the HTML page as well
- The implementation details is very helpful and should included for all tools

**Comment by hughdingb58** [comment]
Went through and implemented most of these.
