### ISSUE TITLE
format_table - Suggestions

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/gen_dw_format#49]
**Code:**
- start indexing at 1 for user, if possible
- implement functionality to remove attributes (style="") in case the user has not used the Dreamweaver formatter

**readme:**
- "For example, inserting the opening thead at row index 0 means placing it before all tr tags (rows). Only the first two row indices given are used. Since thead/tbody/tfoot are only used to group rows, the column indices given above are ignored." --> provide a better example-- it's a bit unclear how to indicate where thead should begin and end (what indices to input)

**Comment by hughdingb58** [comment]
Implemented all
