### ISSUE TITLE
format_toc - Suggestions

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/gen_dw_format#50]
**Code:**
- start indexing at 1, if possible

**readme:**
- "I’m considering integrating this with the Dreamweaver paste formatting tool, but I haven’t yet because unlike the currently pretty safe checks in that tool, this tool is likely to introduce HTML structural errors. Also, the code itself is a lot more involved than other checks." --> is this still applicable?
- "use existing list numberings from the document (explanation #list-numbering)." and "use manually inserted list numberings (differences from using existing list numberings explained #manual-list-numbering)." reference links are broken
- "Misformatting introduced in step 3" --> where/what is step 3?
- "in step 1 (described earlier), to indent the table; and
in step 3, to decide the level of the header tag being linked to." --> label Steps 1, 2, and 3

HTML page:
- move "Before using the tool..." to the top as well as any other relevant information (such as "This tool assumes the input has proper HTML formatting..."
- for the "List type for output table of contents structure", WET4 classes are being used. WET3 is still being used on the external website, so there should be an option for WET3 classes until WET4 is fully implemented
- use a header or differentiate instructions (basically just the "Details on list numberings:" part)

**Comment by hughdingb58** [comment]
Implemented for the most part:
- the reasoning for not integrating with the dreamweaver paste formatting tool is still applicable as this tool does produce structural errors.
- I moved the pre-use warnings to the top of the page but, for brevity, not the explanations of how you should clean up the output afterwards.
- I will deal with WET3 separately
