### ISSUE TITLE
format_bc - Suggestion

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/gen_dw_format#52]
**Code:**
Beyond Compare also differentiates spaces and \&nbsp;s, perhaps adding a function to replace \&nbsp;s with spaces would be helpful (if this makes sense, if not, ignore)

**readme & HTML page:**
Short, concise, and simple.

**Comment by hughdingb58** [comment]
I would do individual character replacements through Beyond Compare itself. I have added a section on this in the readme - let me know if it's clear.

**Comment by stevenli5** [comment]
> I would do individual character replacements through Beyond Compare itself. I have added a section on this in the readme - let me know if it's clear.

Seems pretty clear to me.
