### ISSUE TITLE
format_dw_paste - Suggestions

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/gen_dw_format#53]
**Code:**
- having the option to change all italics and bold to i and b respectively is questionable since it's only for styling purposes
- external website is still using WET3. perhaps give an option to use WET3 classes instead of WET4 (for example, in the readme, the class text-center is used as opposed to align-center)

**readme:**
- Bold headers such as "Format Dreamweaver footnotes:" and "Remove Dreamweaver-generated links:" instead of making them list elements for better visual differentiation

**HTML page:**
- Move the "Before using the tool, make sure that:" and any other important information to the top of the page, so the user performs these tasks before starting
- Maybe add the "Steps to mark superscripts and subscripts in Word" section from the readme to the HTML page, since this process is relatively important and is necessary for subscripts/superscripts. If this is done, "(see the readme for details)" could then be possibly removed

**Comment by hughdingb58** [comment]
will work on the code changes next week, implemented the rest

**Comment by hughdingb58** [comment]
Created a WET4 -> WET3 tool.
